//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Drawing;

namespace Message.UserServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://schemas.datacontract.org/2004/07/ServerWCF.Model")]
    [System.SerializableAttribute()]
    public partial class User : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] AvatarField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<Message.UserServiceReference.BaseContact> ContactsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LoginField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<Message.UserServiceReference.UserToUserContact> OwnersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UnreadMessageCountField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Avatar {
            get {
                return this.AvatarField;
            }
            set {
                if ((object.ReferenceEquals(this.AvatarField, value) != true)) {
                    this.AvatarField = value;
                    this.RaisePropertyChanged("Avatar");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Bio {
            get {
                return this.BioField;
            }
            set {
                if ((object.ReferenceEquals(this.BioField, value) != true)) {
                    this.BioField = value;
                    this.RaisePropertyChanged("Bio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<Message.UserServiceReference.BaseContact> Contacts {
            get {
                return this.ContactsField;
            }
            set {
                if ((object.ReferenceEquals(this.ContactsField, value) != true)) {
                    this.ContactsField = value;
                    this.RaisePropertyChanged("Contacts");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Login {
            get {
                return this.LoginField;
            }
            set {
                if ((object.ReferenceEquals(this.LoginField, value) != true)) {
                    this.LoginField = value;
                    this.RaisePropertyChanged("Login");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<Message.UserServiceReference.UserToUserContact> Owners {
            get {
                return this.OwnersField;
            }
            set {
                if ((object.ReferenceEquals(this.OwnersField, value) != true)) {
                    this.OwnersField = value;
                    this.RaisePropertyChanged("Owners");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Phone {
            get {
                return this.PhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneField, value) != true)) {
                    this.PhoneField = value;
                    this.RaisePropertyChanged("Phone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UnreadMessageCount {
            get {
                return this.UnreadMessageCountField;
            }
            set {
                if ((this.UnreadMessageCountField.Equals(value) != true)) {
                    this.UnreadMessageCountField = value;
                    this.RaisePropertyChanged("UnreadMessageCount");
                }
            }
        }

        private Image _image;

        public Image Images
        {
            get { return _image; }
            set
            {
                _image = value;
                this.RaisePropertyChanged("Images");

            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseContact", Namespace="http://schemas.datacontract.org/2004/07/ServerWCF.Model.Contacts")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Message.UserServiceReference.UserToUserContact))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Message.UserServiceReference.UserToGroupContact))]
    public partial class BaseContact : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Message.UserServiceReference.User UserOwnerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserOwnerIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Message.UserServiceReference.User UserOwner {
            get {
                return this.UserOwnerField;
            }
            set {
                if ((object.ReferenceEquals(this.UserOwnerField, value) != true)) {
                    this.UserOwnerField = value;
                    this.RaisePropertyChanged("UserOwner");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserOwnerId {
            get {
                return this.UserOwnerIdField;
            }
            set {
                if ((this.UserOwnerIdField.Equals(value) != true)) {
                    this.UserOwnerIdField = value;
                    this.RaisePropertyChanged("UserOwnerId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserToUserContact", Namespace="http://schemas.datacontract.org/2004/07/ServerWCF.Model.Contacts")]
    [System.SerializableAttribute()]
    public partial class UserToUserContact : Message.UserServiceReference.BaseContact {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Message.UserServiceReference.User UserOwnedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserOwnedIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Message.UserServiceReference.User UserOwned {
            get {
                return this.UserOwnedField;
            }
            set {
                if ((object.ReferenceEquals(this.UserOwnedField, value) != true)) {
                    this.UserOwnedField = value;
                    this.RaisePropertyChanged("UserOwned");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserOwnedId {
            get {
                return this.UserOwnedIdField;
            }
            set {
                if ((this.UserOwnedIdField.Equals(value) != true)) {
                    this.UserOwnedIdField = value;
                    this.RaisePropertyChanged("UserOwnedId");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserToGroupContact", Namespace="http://schemas.datacontract.org/2004/07/ServerWCF.Model.Contacts")]
    [System.SerializableAttribute()]
    public partial class UserToGroupContact : Message.UserServiceReference.BaseContact {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Message.UserServiceReference.ChatGroup ChatGroupField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ChatGroupIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Message.UserServiceReference.ChatGroup ChatGroup {
            get {
                return this.ChatGroupField;
            }
            set {
                if ((object.ReferenceEquals(this.ChatGroupField, value) != true)) {
                    this.ChatGroupField = value;
                    this.RaisePropertyChanged("ChatGroup");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ChatGroupId {
            get {
                return this.ChatGroupIdField;
            }
            set {
                if ((this.ChatGroupIdField.Equals(value) != true)) {
                    this.ChatGroupIdField = value;
                    this.RaisePropertyChanged("ChatGroupId");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ChatGroup", Namespace="http://schemas.datacontract.org/2004/07/ServerWCF.Model")]
    [System.SerializableAttribute()]
    public partial class ChatGroup : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<Message.UserServiceReference.UserToGroupContact> ParticipantsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<Message.UserServiceReference.UserToGroupContact> Participants {
            get {
                return this.ParticipantsField;
            }
            set {
                if ((object.ReferenceEquals(this.ParticipantsField, value) != true)) {
                    this.ParticipantsField = value;
                    this.RaisePropertyChanged("Participants");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ApplicationSettings", Namespace="http://schemas.datacontract.org/2004/07/ServerWCF.Model")]
    [System.SerializableAttribute()]
    public partial class ApplicationSettings : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool AllowNotificationsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LanguageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ThemeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Message.UserServiceReference.User UserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int WindowSizeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool AllowNotifications {
            get {
                return this.AllowNotificationsField;
            }
            set {
                if ((this.AllowNotificationsField.Equals(value) != true)) {
                    this.AllowNotificationsField = value;
                    this.RaisePropertyChanged("AllowNotifications");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Language {
            get {
                return this.LanguageField;
            }
            set {
                if ((object.ReferenceEquals(this.LanguageField, value) != true)) {
                    this.LanguageField = value;
                    this.RaisePropertyChanged("Language");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Theme {
            get {
                return this.ThemeField;
            }
            set {
                if ((object.ReferenceEquals(this.ThemeField, value) != true)) {
                    this.ThemeField = value;
                    this.RaisePropertyChanged("Theme");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Message.UserServiceReference.User User {
            get {
                return this.UserField;
            }
            set {
                if ((object.ReferenceEquals(this.UserField, value) != true)) {
                    this.UserField = value;
                    this.RaisePropertyChanged("User");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int WindowSize {
            get {
                return this.WindowSizeField;
            }
            set {
                if ((this.WindowSizeField.Equals(value) != true)) {
                    this.WindowSizeField = value;
                    this.RaisePropertyChanged("WindowSize");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GroupMessage", Namespace="http://schemas.datacontract.org/2004/07/ServerWCF.Model.Messages")]
    [System.SerializableAttribute()]
    public partial class GroupMessage : Message.UserServiceReference.BaseMessage {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ChatGroupIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ChatGroupId {
            get {
                return this.ChatGroupIdField;
            }
            set {
                if ((this.ChatGroupIdField.Equals(value) != true)) {
                    this.ChatGroupIdField = value;
                    this.RaisePropertyChanged("ChatGroupId");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseMessage", Namespace="http://schemas.datacontract.org/2004/07/ServerWCF.Model.Messages")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Message.UserServiceReference.UserMessage))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Message.UserServiceReference.GroupMessage))]
    public partial class BaseMessage : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] ContentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateOfSendingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SenderIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Content {
            get {
                return this.ContentField;
            }
            set {
                if ((object.ReferenceEquals(this.ContentField, value) != true)) {
                    this.ContentField = value;
                    this.RaisePropertyChanged("Content");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateOfSending {
            get {
                return this.DateOfSendingField;
            }
            set {
                if ((this.DateOfSendingField.Equals(value) != true)) {
                    this.DateOfSendingField = value;
                    this.RaisePropertyChanged("DateOfSending");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SenderId {
            get {
                return this.SenderIdField;
            }
            set {
                if ((this.SenderIdField.Equals(value) != true)) {
                    this.SenderIdField = value;
                    this.RaisePropertyChanged("SenderId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Type {
            get {
                return this.TypeField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeField, value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserMessage", Namespace="http://schemas.datacontract.org/2004/07/ServerWCF.Model")]
    [System.SerializableAttribute()]
    public partial class UserMessage : Message.UserServiceReference.BaseMessage {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ReceiverIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ReceiverId {
            get {
                return this.ReceiverIdField;
            }
            set {
                if ((this.ReceiverIdField.Equals(value) != true)) {
                    this.ReceiverIdField = value;
                    this.RaisePropertyChanged("ReceiverId");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="UserServiceReference.IUserService", CallbackContract=typeof(Message.UserServiceReference.IUserServiceCallback))]
    public interface IUserService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPhotoService/GetPhotoById", ReplyAction="http://tempuri.org/IPhotoService/GetPhotoByIdResponse")]
        byte[] GetPhotoById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPhotoService/GetPhotoById", ReplyAction="http://tempuri.org/IPhotoService/GetPhotoByIdResponse")]
        System.Threading.Tasks.Task<byte[]> GetPhotoByIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPhotoService/SetPhotoById", ReplyAction="http://tempuri.org/IPhotoService/SetPhotoByIdResponse")]
        void SetPhotoById(int id, byte[] photoBytes);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPhotoService/SetPhotoById", ReplyAction="http://tempuri.org/IPhotoService/SetPhotoByIdResponse")]
        System.Threading.Tasks.Task SetPhotoByIdAsync(int id, byte[] photoBytes);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/GetAllUsers", ReplyAction="http://tempuri.org/IUserService/GetAllUsersResponse")]
        System.Collections.Generic.List<Message.UserServiceReference.User> GetAllUsers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/GetAllUsers", ReplyAction="http://tempuri.org/IUserService/GetAllUsersResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<Message.UserServiceReference.User>> GetAllUsersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/AddOrUpdateUser", ReplyAction="http://tempuri.org/IUserService/AddOrUpdateUserResponse")]
        string AddOrUpdateUser(Message.UserServiceReference.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/AddOrUpdateUser", ReplyAction="http://tempuri.org/IUserService/AddOrUpdateUserResponse")]
        System.Threading.Tasks.Task<string> AddOrUpdateUserAsync(Message.UserServiceReference.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/GetUser", ReplyAction="http://tempuri.org/IUserService/GetUserResponse")]
        Message.UserServiceReference.User GetUser(string login, byte[] password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/GetUser", ReplyAction="http://tempuri.org/IUserService/GetUserResponse")]
        System.Threading.Tasks.Task<Message.UserServiceReference.User> GetUserAsync(string login, byte[] password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/GetUserByEmail", ReplyAction="http://tempuri.org/IUserService/GetUserByEmailResponse")]
        Message.UserServiceReference.User GetUserByEmail(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/GetUserByEmail", ReplyAction="http://tempuri.org/IUserService/GetUserByEmailResponse")]
        System.Threading.Tasks.Task<Message.UserServiceReference.User> GetUserByEmailAsync(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/FindUsersByLogin", ReplyAction="http://tempuri.org/IUserService/FindUsersByLoginResponse")]
        System.Collections.Generic.List<Message.UserServiceReference.User> FindUsersByLogin(string login);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/FindUsersByLogin", ReplyAction="http://tempuri.org/IUserService/FindUsersByLoginResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<Message.UserServiceReference.User>> FindUsersByLoginAsync(string login);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/GetUserByLogin", ReplyAction="http://tempuri.org/IUserService/GetUserByLoginResponse")]
        Message.UserServiceReference.User GetUserByLogin(string login);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/GetUserByLogin", ReplyAction="http://tempuri.org/IUserService/GetUserByLoginResponse")]
        System.Threading.Tasks.Task<Message.UserServiceReference.User> GetUserByLoginAsync(string login);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/AddContact", ReplyAction="http://tempuri.org/IUserService/AddContactResponse")]
        bool AddContact(int id_owner, int id_owned);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/AddContact", ReplyAction="http://tempuri.org/IUserService/AddContactResponse")]
        System.Threading.Tasks.Task<bool> AddContactAsync(int id_owner, int id_owned);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/RemoveContact", ReplyAction="http://tempuri.org/IUserService/RemoveContactResponse")]
        bool RemoveContact(Message.UserServiceReference.User owner, Message.UserServiceReference.User owned);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/RemoveContact", ReplyAction="http://tempuri.org/IUserService/RemoveContactResponse")]
        System.Threading.Tasks.Task<bool> RemoveContactAsync(Message.UserServiceReference.User owner, Message.UserServiceReference.User owned);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/GetAllContacts", ReplyAction="http://tempuri.org/IUserService/GetAllContactsResponse")]
        System.Collections.Generic.List<Message.UserServiceReference.User> GetAllContacts(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/GetAllContacts", ReplyAction="http://tempuri.org/IUserService/GetAllContactsResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<Message.UserServiceReference.User>> GetAllContactsAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/IsExistsInContacts", ReplyAction="http://tempuri.org/IUserService/IsExistsInContactsResponse")]
        bool IsExistsInContacts(int id_owner, int id_owned);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/IsExistsInContacts", ReplyAction="http://tempuri.org/IUserService/IsExistsInContactsResponse")]
        System.Threading.Tasks.Task<bool> IsExistsInContactsAsync(int id_owner, int id_owned);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/GetAppSettings", ReplyAction="http://tempuri.org/IUserService/GetAppSettingsResponse")]
        Message.UserServiceReference.ApplicationSettings GetAppSettings(Message.UserServiceReference.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/GetAppSettings", ReplyAction="http://tempuri.org/IUserService/GetAppSettingsResponse")]
        System.Threading.Tasks.Task<Message.UserServiceReference.ApplicationSettings> GetAppSettingsAsync(Message.UserServiceReference.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/SaveAppSettings", ReplyAction="http://tempuri.org/IUserService/SaveAppSettingsResponse")]
        bool SaveAppSettings(Message.UserServiceReference.ApplicationSettings appSettings);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/SaveAppSettings", ReplyAction="http://tempuri.org/IUserService/SaveAppSettingsResponse")]
        System.Threading.Tasks.Task<bool> SaveAppSettingsAsync(Message.UserServiceReference.ApplicationSettings appSettings);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IUserService/OnUserCame")]
        void OnUserCame(Message.UserServiceReference.User user);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IUserService/OnUserCame")]
        System.Threading.Tasks.Task OnUserCameAsync(Message.UserServiceReference.User user);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IUserService/OnUserLeave")]
        void OnUserLeave(Message.UserServiceReference.User user);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IUserService/OnUserLeave")]
        System.Threading.Tasks.Task OnUserLeaveAsync(Message.UserServiceReference.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/GetGroupMessages", ReplyAction="http://tempuri.org/IUserService/GetGroupMessagesResponse")]
        System.Collections.Generic.List<Message.UserServiceReference.GroupMessage> GetGroupMessages(Message.UserServiceReference.ChatGroup chatGroup, int limin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/GetGroupMessages", ReplyAction="http://tempuri.org/IUserService/GetGroupMessagesResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<Message.UserServiceReference.GroupMessage>> GetGroupMessagesAsync(Message.UserServiceReference.ChatGroup chatGroup, int limin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/GetUserMessages", ReplyAction="http://tempuri.org/IUserService/GetUserMessagesResponse")]
        System.Collections.Generic.List<Message.UserServiceReference.UserMessage> GetUserMessages(int sender, int receiver, int limin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/GetUserMessages", ReplyAction="http://tempuri.org/IUserService/GetUserMessagesResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<Message.UserServiceReference.UserMessage>> GetUserMessagesAsync(int sender, int receiver, int limin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/FindMessage", ReplyAction="http://tempuri.org/IUserService/FindMessageResponse")]
        System.Collections.Generic.List<Message.UserServiceReference.BaseMessage> FindMessage(string keyWord);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/FindMessage", ReplyAction="http://tempuri.org/IUserService/FindMessageResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<Message.UserServiceReference.BaseMessage>> FindMessageAsync(string keyWord);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IUserService/SendMessage")]
        void SendMessage(Message.UserServiceReference.BaseMessage message);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IUserService/SendMessage")]
        System.Threading.Tasks.Task SendMessageAsync(Message.UserServiceReference.BaseMessage message);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IUserService/EditMessage")]
        void EditMessage(Message.UserServiceReference.BaseMessage editedMessage);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IUserService/EditMessage")]
        System.Threading.Tasks.Task EditMessageAsync(Message.UserServiceReference.BaseMessage editedMessage);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IUserService/RemoveMessage")]
        void RemoveMessage(Message.UserServiceReference.BaseMessage removedMessage);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IUserService/RemoveMessage")]
        System.Threading.Tasks.Task RemoveMessageAsync(Message.UserServiceReference.BaseMessage removedMessage);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUserServiceCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IUserService/UserLeave")]
        void UserLeave(Message.UserServiceReference.User user);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IUserService/UserCame")]
        void UserCame(Message.UserServiceReference.User user);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IUserService/ReceiveMessage")]
        void ReceiveMessage(Message.UserServiceReference.BaseMessage message);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IUserService/OnMessageRemoved")]
        void OnMessageRemoved(Message.UserServiceReference.BaseMessage message);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IUserService/OnMessageEdited")]
        void OnMessageEdited(Message.UserServiceReference.BaseMessage message);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUserServiceChannel : Message.UserServiceReference.IUserService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UserServiceClient : System.ServiceModel.DuplexClientBase<Message.UserServiceReference.IUserService>, Message.UserServiceReference.IUserService {
        
        public UserServiceClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public UserServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public UserServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public UserServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public UserServiceClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public byte[] GetPhotoById(int id) {
            return base.Channel.GetPhotoById(id);
        }
        
        public System.Threading.Tasks.Task<byte[]> GetPhotoByIdAsync(int id) {
            return base.Channel.GetPhotoByIdAsync(id);
        }
        
        public void SetPhotoById(int id, byte[] photoBytes) {
            base.Channel.SetPhotoById(id, photoBytes);
        }
        
        public System.Threading.Tasks.Task SetPhotoByIdAsync(int id, byte[] photoBytes) {
            return base.Channel.SetPhotoByIdAsync(id, photoBytes);
        }
        
        public System.Collections.Generic.List<Message.UserServiceReference.User> GetAllUsers() {
            return base.Channel.GetAllUsers();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<Message.UserServiceReference.User>> GetAllUsersAsync() {
            return base.Channel.GetAllUsersAsync();
        }
        
        public string AddOrUpdateUser(Message.UserServiceReference.User user) {
            return base.Channel.AddOrUpdateUser(user);
        }
        
        public System.Threading.Tasks.Task<string> AddOrUpdateUserAsync(Message.UserServiceReference.User user) {
            return base.Channel.AddOrUpdateUserAsync(user);
        }
        
        public Message.UserServiceReference.User GetUser(string login, byte[] password) {
            return base.Channel.GetUser(login, password);
        }
        
        public System.Threading.Tasks.Task<Message.UserServiceReference.User> GetUserAsync(string login, byte[] password) {
            return base.Channel.GetUserAsync(login, password);
        }
        
        public Message.UserServiceReference.User GetUserByEmail(string email) {
            return base.Channel.GetUserByEmail(email);
        }
        
        public System.Threading.Tasks.Task<Message.UserServiceReference.User> GetUserByEmailAsync(string email) {
            return base.Channel.GetUserByEmailAsync(email);
        }
        
        public System.Collections.Generic.List<Message.UserServiceReference.User> FindUsersByLogin(string login) {
            return base.Channel.FindUsersByLogin(login);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<Message.UserServiceReference.User>> FindUsersByLoginAsync(string login) {
            return base.Channel.FindUsersByLoginAsync(login);
        }
        
        public Message.UserServiceReference.User GetUserByLogin(string login) {
            return base.Channel.GetUserByLogin(login);
        }
        
        public System.Threading.Tasks.Task<Message.UserServiceReference.User> GetUserByLoginAsync(string login) {
            return base.Channel.GetUserByLoginAsync(login);
        }
        
        public bool AddContact(int id_owner, int id_owned) {
            return base.Channel.AddContact(id_owner, id_owned);
        }
        
        public System.Threading.Tasks.Task<bool> AddContactAsync(int id_owner, int id_owned) {
            return base.Channel.AddContactAsync(id_owner, id_owned);
        }
        
        public bool RemoveContact(Message.UserServiceReference.User owner, Message.UserServiceReference.User owned) {
            return base.Channel.RemoveContact(owner, owned);
        }
        
        public System.Threading.Tasks.Task<bool> RemoveContactAsync(Message.UserServiceReference.User owner, Message.UserServiceReference.User owned) {
            return base.Channel.RemoveContactAsync(owner, owned);
        }
        
        public System.Collections.Generic.List<Message.UserServiceReference.User> GetAllContacts(int id) {
            return base.Channel.GetAllContacts(id);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<Message.UserServiceReference.User>> GetAllContactsAsync(int id) {
            return base.Channel.GetAllContactsAsync(id);
        }
        
        public bool IsExistsInContacts(int id_owner, int id_owned) {
            return base.Channel.IsExistsInContacts(id_owner, id_owned);
        }
        
        public System.Threading.Tasks.Task<bool> IsExistsInContactsAsync(int id_owner, int id_owned) {
            return base.Channel.IsExistsInContactsAsync(id_owner, id_owned);
        }
        
        public Message.UserServiceReference.ApplicationSettings GetAppSettings(Message.UserServiceReference.User user) {
            return base.Channel.GetAppSettings(user);
        }
        
        public System.Threading.Tasks.Task<Message.UserServiceReference.ApplicationSettings> GetAppSettingsAsync(Message.UserServiceReference.User user) {
            return base.Channel.GetAppSettingsAsync(user);
        }
        
        public bool SaveAppSettings(Message.UserServiceReference.ApplicationSettings appSettings) {
            return base.Channel.SaveAppSettings(appSettings);
        }
        
        public System.Threading.Tasks.Task<bool> SaveAppSettingsAsync(Message.UserServiceReference.ApplicationSettings appSettings) {
            return base.Channel.SaveAppSettingsAsync(appSettings);
        }
        
        public void OnUserCame(Message.UserServiceReference.User user) {
            base.Channel.OnUserCame(user);
        }
        
        public System.Threading.Tasks.Task OnUserCameAsync(Message.UserServiceReference.User user) {
            return base.Channel.OnUserCameAsync(user);
        }
        
        public void OnUserLeave(Message.UserServiceReference.User user) {
            base.Channel.OnUserLeave(user);
        }
        
        public System.Threading.Tasks.Task OnUserLeaveAsync(Message.UserServiceReference.User user) {
            return base.Channel.OnUserLeaveAsync(user);
        }
        
        public System.Collections.Generic.List<Message.UserServiceReference.GroupMessage> GetGroupMessages(Message.UserServiceReference.ChatGroup chatGroup, int limin) {
            return base.Channel.GetGroupMessages(chatGroup, limin);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<Message.UserServiceReference.GroupMessage>> GetGroupMessagesAsync(Message.UserServiceReference.ChatGroup chatGroup, int limin) {
            return base.Channel.GetGroupMessagesAsync(chatGroup, limin);
        }
        
        public System.Collections.Generic.List<Message.UserServiceReference.UserMessage> GetUserMessages(int sender, int receiver, int limin) {
            return base.Channel.GetUserMessages(sender, receiver, limin);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<Message.UserServiceReference.UserMessage>> GetUserMessagesAsync(int sender, int receiver, int limin) {
            return base.Channel.GetUserMessagesAsync(sender, receiver, limin);
        }
        
        public System.Collections.Generic.List<Message.UserServiceReference.BaseMessage> FindMessage(string keyWord) {
            return base.Channel.FindMessage(keyWord);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<Message.UserServiceReference.BaseMessage>> FindMessageAsync(string keyWord) {
            return base.Channel.FindMessageAsync(keyWord);
        }
        
        public void SendMessage(Message.UserServiceReference.BaseMessage message) {
            base.Channel.SendMessage(message);
        }
        
        public System.Threading.Tasks.Task SendMessageAsync(Message.UserServiceReference.BaseMessage message) {
            return base.Channel.SendMessageAsync(message);
        }
        
        public void EditMessage(Message.UserServiceReference.BaseMessage editedMessage) {
            base.Channel.EditMessage(editedMessage);
        }
        
        public System.Threading.Tasks.Task EditMessageAsync(Message.UserServiceReference.BaseMessage editedMessage) {
            return base.Channel.EditMessageAsync(editedMessage);
        }
        
        public void RemoveMessage(Message.UserServiceReference.BaseMessage removedMessage) {
            base.Channel.RemoveMessage(removedMessage);
        }
        
        public System.Threading.Tasks.Task RemoveMessageAsync(Message.UserServiceReference.BaseMessage removedMessage) {
            return base.Channel.RemoveMessageAsync(removedMessage);
        }
    }
}
